-- 사수가 없는 사원은 누구냐
SELECT *
FROM EMP
WHERE MGR IS NULL;
-- 부서 정보가 없는 사원은 누구냐
UPDATE EMP SET DEPTNO = 50 WHERE EMPNO = 7839;


--1. NOT EXISTS 권장한다
SELECT *
FROM EMP E 
WHERE NOT EXISTS (
    SELECT 1 FROM DEPT D
    WHERE D.DEPTNO = E.DEPTNO
    );

--2. NOT IN
SELECT *
FROM EMP
WHERE DEPTNO NOT IN (
                SELECT DEPTNO
                FROM dept
                WHERE DEPTNO IS NOT NULL);
                
--3. LEFT JOIN
    SELECT *
    FROM EMP E
    LEFT OUTER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO;
    
    SELECT *
    FROM EMP E
    INNER JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO;
    
    
    
-- 실습 9-18
SELECT *
  FROM EMP
 WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                           FROM EMP
                         GROUP BY DEPTNO);

-- 실습 9-19
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
       (SELECT * FROM DEPT) D
 WHERE E10.DEPTNO = D.DEPTNO;

-- 실습 9-20
WITH
E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10),
D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM E10, D
 WHERE E10.DEPTNO = D.DEPTNO;

-- 실습 9-21
SELECT EMPNO, ENAME, JOB, SAL,
       (SELECT GRADE 
          FROM SALGRADE
         WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DEPTNO,
      (SELECT DNAME
         FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;