select * from emp;
select ename, ename, deptno from emp;
SELECT DISTINCT DEPTNO FROM EMP;
SELECT DISTINCT JOB, DEPTNO FROM EMP;
SELECT ENAME,SAL*12 AS ANSAL FROM EMP;
SELECT * FROM EMP ORDER BY SAL DESC; 
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC;
SELECT * 
    FROM EMP 
    WHERE DEPTNO = 30 
    AND JOB = 'SALESMAN';
SELECT * 
    FROM EMP 
    WHERE DEPTNO = 30 
    OR JOB = 'CLERK';
SELECT * 
    FROM EMP 
    WHERE SAL >= 3000;
SELECT * 
    FROM EMP 
    WHERE NOT SAL = 3000;
SELECT * 
    FROM EMP 
    WHERE JOB IN('MANAGER', 'CLERK', 'SALESMAN');
SELECT * 
    FROM EMP 
    WHERE JOB NOT IN('MANAGER', 'CLERK', 'SALESMAN');
SELECT * 
    FROM EMP 
    WHERE SAL BETWEEN 2000 AND 3000;
SELECT * 
    FROM EMP 
    WHERE ENAME LIKE '%AM%';
SELECT * 
    FROM EMP 
    WHERE DEPTNO = 10
UNION
    SELECT * 
    FROM EMP 
    WHERE DEPTNO = 20;

SELECT * 
    FROM EMP 
    WHERE DEPTNO = 10
UNION ALL
    SELECT * 
    FROM EMP 
    WHERE DEPTNO = 10;
    
SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS') AS 현재날짜시간 
    FROM DUAL;
    
SELECT TO_NUMBER(SYSDATE, 'YY/MM/DD HH24:MI:SS') AS 현재날짜시간 
    FROM DUAL;

SELECT * FROM EMP;

--시험에 나올수도있음 필수
SELECT ENAME, SAL, NVL(COMM, 0) AS COMMISSION
FROM EMP;
--3항연산자
SELECT NVL2(COMM, 'O','X') AS COMMISSION
FROM EMP;

--3항 연산자의 친구
SELECT DECODE(JOB,
            'MANAGER', SAL*1.1,
            'SALESMAN', SAL*1.05,
            'ANALYST', SAL,
            SAL*1.03) AS UPSAL
    FROM EMP;
    
--숫자함수
--

--JOIN 기억안났음
SELECT * FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT * FROM EMP, DEPT 
WHERE EMP.DEPTNO = DEPT.DEPTNO;

--셀프조인
-- 메니저 보여줌
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

--사원은 있는데 메니저가 없는 것을 찾아내라
--레프트 조인인데, 풀네임은 레프트 아우터 조인이다.
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+); -- 매니저 데이터가 없어도 사원(E1)은 다 보여줘!

-- 부서별 사원수 매우중요!! 집계함수와 그룹바이
SELECT COUNT(EMPNO), DEPTNO
FROM EMP
GROUP BY DEPTNO;

--서브쿼리
SELECT * FROM EMP 
WHERE SAL >(SELECT SAL 
            FROM EMP 
            WHERE ENAME = 'JONES') 
;