SELECT MAX(SAL)
  FROM EMP
 WHERE DEPTNO = 10;
 
 SELECT AVG(SAL), DEPTNO
    FROM EMP
 GROUP BY DEPTNO;
 
SELECT MIN(SAL)
    FROM
WHERE DEPTNO = 20;

SELECT AVG(SAL)
;
-- 실습 7-18
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;


-- 실습 7-23
SELECT DEPTNO, JOB, AVG(SAL)
  FROM EMP
 WHERE SAL <= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;