create table dept_temp as select * from dept;

CREATE TABLE EMP_TEMP
    AS SELECT *
         FROM EMP
        WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND S.GRADE = 1;
   
   CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL';
   
   rollback;
   
  UPDATE DEPT_TEMP2
   SET DNAME = 'DATABASE',
         LOC = 'SEOUL'
 WHERE DEPTNO = 40;
 
 -- 실습 10-20
UPDATE DEPT_TEMP2
   SET DNAME = (SELECT DNAME
                  FROM DEPT
                 WHERE DEPTNO = 40),
       LOC = (SELECT LOC
                FROM DEPT
               WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;
 
 DELETE FROM EMP_TEMP2
 WHERE EMPNO IN (SELECT E.EMPNO
                   FROM EMP_TEMP2 E, SALGRADE S
                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DEPTNO = 30);
 create index idx_emp_sal on emp(sal);
 
 create index IDX_EMP_SAL ON EMP(SAL);
 
 GRANT CREATE VIEW TO SCOTT;
 
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
          FROM EMP
         WHERE DEPTNO = 20);

-- 페이징
SELECT ROWNUM, E.*
 FROM EMP E;
 
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
   INCREMENT BY 10
   START WITH 10
   MAXVALUE 90
   MINVALUE 0
   NOCYCLE
   CACHE 2;
   
SELECT SEQ_DEPT_SEQUENCE.NEXTVAL
   FROM DUAL;
   
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
   FROM DUAL;
   
SELECT SEQ_DEPT_SEQUENCE.NEXTVAL
    FROM DUAL;

CREATE SYNONYM E;

SELECT * FROM E;
CREATE SYNONYM E
   FOR EMP;


CREATE OR REPLACE FUNCTION add_numbers(
    p_num1 NUMBER,
    p_num2 NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN p_num1 + p_num2;
END;
/

select add_numbers(1,2)
from dual;