 GRANT CREATE VIEW TO SCOTT;

GRANT CREATE SEQUENCE TO SCOTT;

SQLPLUS SYSTEM/oracle

GRANT CREATE SYNONYM TO SCOTT;

GRANT CREATE PUBLIC SYNONYM TO SCOTT;

-- 실습 13-39
;
--funtion
CREATE OR REPLACE FUNCTION add_numbers(
    p_num1 NUMBER,
    p_num2 NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN p_num1 + p_num2;
END;
/

GRANT CREATE procedure TO scott;